### ISSUE TITLE
Change background image

### ISSUE THREAD

**Issue by qtrandev** [CodeForFtL/OpenDataPolicy#3]
Look for the .sass files.

**Comment by qtrandev** [comment]
@daarons Any idea what to fix?

**Comment by qtrandev** [comment]
Uploaded new background image from daarons commit. CSS needs to be changed eventually to ftl name, but avoiding .sass files for now. 35332606e96e6d23de3fc00f937f6ae098713e39

**Comment by daarons** [comment]
My b, just saw this.
